<a href="https://colab.research.google.com/github/Prabinkarki67/Spam-Email-Detector-/blob/main/emailDetector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Spam Email Detection

```
# This is formatted as code
```

## Load Dataset

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("subhajournal/phishingemails")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/subhajournal/phishingemails/1.archive...

100%|██████████| 18.0M/18.0M [00:00<00:00, 125MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/subhajournal/phishingemails/versions/1

In [2]:
import os

os.listdir(path)

['Phishing_Email.csv']

In [3]:
import pandas as pd
import os

csv_file = os.path.join(path, "Phishing_Email.csv")

df = pd.read_csv(csv_file)

df.head()

,Unnamed: 0,Email Text,Email Type
0,0,"re : 6 . 1100 , disc : uniformitarianism , re ...",Safe Email
1,1,the other side of * galicismos * * galicismo *...,Safe Email
2,2,re : equistar deal tickets are you still avail...,Safe Email
3,3,\nHello I am your hot lil horny toy.\n I am...,Phishing Email
4,4,software at incredibly low prices ( 86 % lower...,Phishing Email

## EDA

In [4]:
df.dropna(subset=['Email Text'], inplace=True)

In [5]:
df.isnull().sum()

Unnamed: 0    0
Email Text    0
Email Type    0
dtype: int64

In [6]:
df['Email Type'].value_counts()

Email Type
Safe Email        11322
Phishing Email     7312
Name: count, dtype: int64

## Preprocessing

In [7]:
df['Email Type'] = df['Email Type'].map(
    {    'Safe Email': 1,
    'Phishing Email': 0}
    )

df

,Unnamed: 0,Email Text,Email Type
0,0,"re : 6 . 1100 , disc : uniformitarianism , re ...",1
1,1,the other side of * galicismos * * galicismo *...,1
2,2,re : equistar deal tickets are you still avail...,1
3,3,\nHello I am your hot lil horny toy.\n I am...,0
4,4,software at incredibly low prices ( 86 % lower...,0
...,...,...,...
18645,18646,date a lonely housewife always wanted to date ...,0
18646,18647,request submitted : access request for anita ....,1
18647,18648,"re : important - prc mtg hi dorn & john , as y...",1
18648,18649,press clippings - letter on californian utilit...,1
18649,18650,empty,0

## Tokenization and stopwords treatement

In [8]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [9]:
df['Email Text'].isnull().sum()

np.int64(0)

In [10]:
swords = stopwords.words('english')

In [11]:
df['Email Text'] = df['Email Text'].apply(lambda x: x.split())

In [12]:
cleaned = []

for words in df['Email Text']:

    new_words = []

    for word in words:
        if word.lower() not in swords:
            new_words.append(word)

    cleaned.append(new_words)

df['Email Text'] = cleaned

In [13]:
df

,Unnamed: 0,Email Text,Email Type
0,0,"[:, 6, ., 1100, ,, disc, :, uniformitarianism,...",1
1,1,"[side, *, galicismos, *, *, galicismo, *, span...",1
2,2,"[:, equistar, deal, tickets, still, available,...",1
3,3,"[Hello, hot, lil, horny, toy., one, dream, Abo...",0
4,4,"[software, incredibly, low, prices, (, 86, %, ...",0
...,...,...,...
18645,18646,"[date, lonely, housewife, always, wanted, date...",0
18646,18647,"[request, submitted, :, access, request, anita...",1
18647,18648,"[:, important, -, prc, mtg, hi, dorn, &, john,...",1
18648,18649,"[press, clippings, -, letter, californian, uti...",1
18649,18650,[empty],0

In [14]:
df['Email Text'] = df['Email Text'].apply(lambda x: ' '.join(x))
df

,Unnamed: 0,Email Text,Email Type
0,0,": 6 . 1100 , disc : uniformitarianism , : 1086...",1
1,1,side * galicismos * * galicismo * spanish term...,1
2,2,: equistar deal tickets still available assist...,1
3,3,"Hello hot lil horny toy. one dream About, open...",0
4,4,software incredibly low prices ( 86 % lower ) ...,0
...,...,...,...
18645,18646,date lonely housewife always wanted date lonel...,0
18646,18647,request submitted : access request anita . dup...,1
18647,18648,": important - prc mtg hi dorn & john , discove...",1
18648,18649,press clippings - letter californian utilities...,1
18649,18650,empty,0

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

## Model Creation

### train test split

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X = df['Email Text'].values
y = df['Email Type'] .values

In [17]:
X

array([': 6 . 1100 , disc : uniformitarianism , : 1086 ; sex / lang dick hudson \'s observations us use \'s \' \'d aughter \' vocative thought-provoking , sure fair attribute " sons " " treated like senior relatives " . one thing , n\'t normally use \' brother \' way \'d aughter \' , hard imagine natural class comprising senior relatives \'s \' excluding \' brother \' . another , seem differences . imagining distinction , seems senior relative terms used wider variety contexts , e . g . , calling distance get someone \'s attention , hence beginning utterance , whereas \'s \' seems natural utterances like \' yes , son \' , \' hand , son \' ones like \' son ! \' \' son , help ! \' ( although perhaps latter ones completely impossible ) . alexis mr',
       'side * galicismos * * galicismo * spanish term names improper introduction french words spanish sounding thus deceptive ear . * galicismo * often considered * barbarismo * . would term designates opposite phenomenon , unlawful words spanish origin may crept french ? someone provide examples ? thank joseph kozono < kozonoj @ gunet . georgetown . edu >',
       ": equistar deal tickets still available assist robert entering new deal tickets equistar ? talking bryan hull anita luong , kyle decided need 1 additional sale ticket 1 additional buyback ticket set . - - - - - - - - - - - - - - - - - - - - - - forwarded tina valadez / hou / ect 04 / 06 / 2000 12 : 56 pm - - - - - - - - - - - - - - - - - - - - - - - - - - - : robert e lloyd 04 / 06 / 2000 12 : 40 pm : tina valadez / hou / ect @ ect cc : subject : : equistar deal tickets ' may want run idea daren farmer . ' normally add tickets sitara . tina valadez 04 / 04 / 2000 10 : 42 : robert e lloyd / hou / ect @ ect cc : bryan hull / hou / ect @ ect subject : equistar deal tickets kyle met bryan hull morning decided need 1 new sale ticket 1 new buyback ticket set . time period tickets july 1999 - forward . pricing new sale ticket like tier 2 sitara # 156337 : pricing new buyback ticket like tier 2 sitara # 156342 : questions , please let know . thanks , tina valadez 3 - 7548",
       ...,
       ": important - prc mtg hi dorn & john , discovered recently , still ' officially ' vince kaminski ' group ( original enron corp . group ) . holds true shalesh ganjoo well . explicitly pick dorn john reviewers thinking show automatically result assumed reporting structure . , vince agreed ' host ' review group proceed transfer ebs officially quarter overs ( apprently scheduled automatic ) . mean time , vasant , stinson vince would like get e - mail either dorn john regarding performance perspective consideration soon possible . plan vacation starting tomorrow made arrangement family already . since reviewing shalesh directly ( since research stionson ) , assuming ' attend review meetin tommorrow . ' road starting morning . change , told home , market another family ! phone okay . kayla , could page details ? regards , ravi .",
       "press clippings - letter californian utilities please find attached following article : ' californian utilities ' - financial times ( also sent california distribution team ) kind regards , kuldeep chana",
       'empty'], dtype=object)

In [18]:
X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size = 0.2, random_state=2)

### Vectorization

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer()

X_train = vect.fit_transform(X_train)
X_test = vect.transform(X_test)

### Model Fitting

In [20]:
from sklearn.linear_model import LogisticRegression as lr
model = lr(max_iter=1000)

In [21]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

## Model Evaluation

In [22]:
from sklearn.metrics import accuracy_score as Acc
y_pred   = model.predict(X_test)
acc = Acc(y_test, y_pred)
print(acc)

0.9710222699221894

In [23]:
from sklearn.metrics import accuracy_score as Acc
y_pred   = model.predict(X_train)
acc = Acc(y_train, y_pred)
print(acc)

0.9834976856510365

## Input Given

### Load Input and preprocessing

In [28]:
ip = input("Enter the email: ")
ip = ip.split()
ip = [i for i in ip if i not in swords]
ip = ' '.join(ip)

Enter the email: hello sir this is 1x bet sign in to continue

### Predict output

In [29]:
ip_vect = vect.transform([ip])
op = model.predict(ip_vect)
if op[0] == 0:
  print('Phishing Email')
else:
  print('Safe Email')

Phishing Email

In [31]:
import joblib

# Save model
joblib.dump(model, "model.pkl")

['model.pkl']